$(document).ready(function(){
    $(".hero-caro").owlCarousel({
        items:1,
        dots:false,
        nav:true,
        loop:true,
        autoplay:true,
        autoplayTimeout:3000
    });
    $(".latest-post-carousel").owlCarousel({
       
        loop:true,
        margin:20,
        autoplay:true,
        autoplayTimeout:3000,
        responsive:{
            0:{
                items:1
            },
            768:{
                items:2
            },
            992:{
                items:3
            }
        }
    });
    AOS.init();
});